### ISSUE TITLE
Change JMCCC's license

### ISSUE THREAD

**Issue by yushijinhun** [to2mbn/JMCCC#16]
Recent days, we discovered that the Unlicense was too open. It allows everyone to use or modify the source code, which might cause some problems. So we finally decided to change the license of JMCCC to MIT license.

The old commits will be still under Unlicense. And the new ones will be under MIT License.

In order to change the license of JMCCC, we need contributors' agreements.
The following is the contributor list. (Strikethrough means we have already got the contributor's agreement.)
 * ~~@zhoulifu~~
 * ~~@Darkyoooooo~~
 * ~~@yushijinhun~~

If you are in the list above, and you agree to change the license, please reply with something along the words of: "I permit the license of my contributions to JMCCC project to be changed to the MIT License."

**Comment by Darkyoooooo** [comment]
I permit the license of my contributions to JMCCC project to be changed to the MIT License. :)

**Comment by Srar** [comment]
I permit the license of my contributions to JMCCC project to be changed to the MIT License. :)

**Comment by yushijinhun** [comment]
@Srar - You don't have contributions to JMCCC;)

**Comment by zhoulifu** [comment]
I permit the license of my contributions to JMCCC project to be changed to the MIT License.

**Comment by yushijinhun** [comment]
@zhoulifu - That's ok.

All the contributors have agreed to change the license.
