### ISSUE TITLE
我已经导入证书了  怎么还是这样？

### ISSUE THREAD

**Issue by ChenHauShen** [to2mbn/JMCCC#17]
[INFO] Scanning for projects...
[INFO] Downloading: https://maven.lazercloud.com/nexus/content/groups/public/org/sonatype/plugins/nexus-staging-maven-plugin/1.6.6/nexus-staging-maven-plugin-1.6.6.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.6 @ 
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.to2mbn:jmccc-parent:3.0-SNAPSHOT (C:\Users\Anyways\Desktop\JMCCC\JMCCC\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.sonatype.plugins:nexus-staging-maven-plugin:1.6.6 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.sonatype.plugins:nexus-staging-maven-plugin:jar:1.6.6: Could not transfer artifact org.sonatype.plugins:nexus-staging-maven-plugin:pom:1.6.6 from/to maven-Lazercloud-cn (https://maven.lazercloud.com/nexus/content/groups/public/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by yushijinhun** [comment]
我看这个应该是您使用的Maven镜像站的问题，`https://maven.lazercloud.com/`的证书可能有错误。我推荐您最好还是使用Maven中心仓库，或者使用[oschina的镜像站](http://maven.oschina.net/content/groups/public/)。
