### ISSUE TITLE
无法启动安装了mcheli的1.7.10客户端

### ISSUE THREAD

**Issue by lj2000lj** [to2mbn/JMCCC#19]
Jmccc调用代码与http://www.mcbbs.net/thread-573154-1-1.html中所示一致
Forge日志文件显示如下：
[时间] [Client thread/ERROR]: Found a duplicate mod mcheli at [路径\.minecraft, 路径\.minecraft\mods\mcheli]
之前有显示mcheli加载了两次，一次不能找到mcmod.info，第二次可以找到。
如果将mcheli放入mods下的1.7.10文件夹，forge会多识别出一个mcheli，并且依旧不能找到mcmod.info
其他启动器正常，MinecraftForum上有提到一款名为FTB Launcher的启动器存在同样的问题

**Comment by yushijinhun** [comment]
感谢您的反馈。不知您能否附上Minecraft和Forge的版本，以及mod的版本（mod最好是附上文件），以便重现bug？

**Comment by lj2000lj** [comment]
Forge版本为1.7.10-10.13.4.1558
mod为mcheli 0.10.8 只修改过部分材质和mod配置文件，与未经修改的mod基本没有区别
mod发布地址http://forum.minecraftuser.jp/viewtopic.php?t=14837

**Comment by Darkyoooooo** [comment]
可否附上完整的crash-log？

**Comment by lj2000lj** [comment]
是正常的Forge退出，没有crash-log
和错误相关的日志只有这一行
[时间] [Client thread/ERROR]: Found a duplicate mod mcheli at [路径.minecraft, 路径.minecraft\mods\mcheli]
同一个mod加载了两次，而且确实是只有一个mod，而且其中一个路径直接是.minecraft

MinecraftForum上有提到和解压的mod有关

**Comment by yushijinhun** [comment]
确认是bug。jmccc的`-cp`末尾多了个`:`（路径分隔符）。

**Comment by yushijinhun** [comment]
commit已经合并到了master，你可以从master上拉取代码（或使用`2.5-SNAPSHOT`这个版本）测试一下bug是否被修复了。
