### ISSUE TITLE
Can't launch 1.7.10 forge?

### ISSUE THREAD

**Issue by MrManiacc** [to2mbn/JMCCC#22]
Hi, when attempting to launch 1.7.10 forge (1.7.10-forge1.7.10-10.13.0.1180), but when launching any version > 1.7.10 like 1.8 the program launches perfectly. Nothing different in the console, it just simply won't launch 1.7.10

**Comment by yushijinhun** [comment]
Could you add the following two fml parameters and then try again?
https://github.com/to2mbn/JMCCC/blob/master/README.md#fml-options
