### ISSUE TITLE
Can't download Forge or Liteloader

### ISSUE THREAD

**Issue by coolnickname** [to2mbn/JMCCC#23]
Error exception thrown at an attempt to download Forge (1.8-forge1.8-11.14.3.1514):
http://pastebin.com/fE5gfJm7
This does create a Forge folder in the versions folder.

Error exception thrown at an attempt to download Liteloader(1.8-LiteLoader1.8):
http://pastebin.com/uw87GqLY
This does not make a Liteloader folder and appears to happen during a sub download as it shows the retry message which is only printed if the downloading fails during a sub download.

This is most likely my own fault so please tell me what I'm doing wrong, thanks in advance.

**Comment by yushijinhun** [comment]
I noticed that you hadn't add the dependency `org.tukaani:xz` to classpath. The dependency is used when installing forge.

**Comment by coolnickname** [comment]
Euhm, how would I do that?

**Comment by yushijinhun** [comment]
If you're using gradle/maven, they will do this for you. If you manage dependencies manually, you can download it from https://search.maven.org/#artifactdetails%7Corg.tukaani%7Cxz%7C1.6%7Cjar

I will test liteloader downloading later.
