### ISSUE TITLE
jmccc 3.0

### ISSUE THREAD

**Issue by yushijinhun** [to2mbn/JMCCC#25]
* [x] 将version升至3.0-SNAPSHOT
* [x] 将java版本切换为java8
* [ ] 完全重写
    * 语言为kotlin

...其它项目还在考虑中

**Comment by CraftLifeGaming** [comment]
Can you add support for the old bin folder structure, but for any version of the game? I'm trying to launch Technic Launcher packs, and they use the bin structure. And yeah, I know I can just use the Technic Launcher, I'm just doing it for convenience mostly.

**Comment by yushijinhun** [comment]
@CraftLifeGaming I'm sorry that we don't have any plan to support the old directory structure, which was used years ago and now is completely out-of-date.
But I think the old structure is simple enough that you don't even need a library to do the launching work. You can start the game just using commandline `java -jar .minecraft` with a few parameters such as `accessToken`. I hope this can help you.

**Comment by IzzelAliz** [comment]
Kotlin 这个，毕竟作为一个库，还是纯 java 比较好

希望添加对 1.13 snapshot 启动的支持

**Comment by NanamiArihara** [comment]
no kotlin
