### ISSUE TITLE
1.7.2版本资源文件问题

### ISSUE THREAD

**Issue by DoraJDJ** [to2mbn/JMCCC#9]
继上回 Issues #8 的延伸

### 主要问题
虽然在 #8 内对于1.7.2及以下版本无法直接启动的问题已经解决，但是近日本人测试的时候发现系统并没有自动生成“虚拟”文件夹（assets/virtual/）并使用，结果发生了一系列搞怪的问题：

![已设置简体中文语言，但依旧显示英文](http://img.cirno.biz/di/21JO/Minecraft_1.png)
> 已设置简体中文语言，但依旧显示英文

![indexes文件正常](http://img.cirno.biz/di/HME8/indexes_031.png)
> indexes文件正常

![语言文件也没有任何损坏](http://img.cirno.biz/di/SR6P/选区_032.png)
> 语言文件也没有任何损坏

### 解决方案
个人设想的解决方案是：像正版启动器那样工作，读取indexes文件，然后将那些以hash值为文件名的文件重命名为原来的文件名，然后统一放到virtual/legacy文件夹里，接着让Minecraft读取使用。

十分抱歉为开发人员添加工作量，但十分希望能尽快解决！
thx

**Comment by yushijinhun** [comment]
验证一下master或longteam-2.3.x分支上这个bug是不是已经修复了
